#!/bin/bash


# 4.31 - moje reseni
: <<'END'  # tvorba cvicnych souboru nebo seq 1 20 | xargs -I {} touch /tmp/testy{}
i=1
while [ "$i" -le 20 ]; do
	touch /tmp/testy$i
	i=$((i + 1))
done
END

touch hledani
find "$@" > hledani
filename='hledani'
iterace=0

: << 'END'
while read line; do
	echo "$line"
	read -p "Chces soubor $line opravdu smazat?  " odpoved
	echo "$odpoved"
	#case "$odpoved" in
	#	ano ) rm "$line";;
	#	ne ) continue;;
	#	stop ) break; exit;;
	#esac
	iterace=$((iterace + 1))
	echo "$iterace" "chachacha"
done < $filename
END

while read line; do
	echo "$line"
	read -p "Chces soubor $line opravdu smazat?  " odpoved
	case "$odpoved" in
		ano ) rm "$line";;
		ne ) continue;;
		stop ) break; exit;;
	esac
	iterace=$((iterace + 1))
	echo "$iterace"
done < $filename








