#!/bin/bash


# 4.31 - moje reseni
: <<'END'  # tvorba cvicnych souboru
i=1
while [ "$i" -le 20 ]; do
	touch /tmp/testy$i
	i=$((i + 1))
done
END


soubory=$(find . -wholename "$1")
iterace=1
for i in "$soubory"; do
	read -p "Chces soubor "$i" opravdu smazat?  " odpoved
	case "$odpoved" in
		ano ) rm "$i";;
		ne ) continue;;
		stop ) break; exit;;
	esac

	iterace=$((iterace + 1))
	echo "$iterace"
done









