#!/bin/bash

# cv. 4.32 
# 3. varianta
projdi() {
	set -- "$1"/*  # vlozeni seznamu souboru v adresari do pozicnich parametru
	while [ "$#" -gt 0 ]; do
		[ -d "$1" -a ! -L "$1" ] && projdi "$1" && return 0
		case "$1" in
		$vzor | */$vzor ) echo "$1"; return 0;;  # co znamena */$vzor?
		esac
		shift
	done
	return 1
}
vzor=$1 projdi "$2"

# pozicni parametry jsou ve funkcich lokalni
