#!/bin/sh
# priklad 4.24; moje reseni - nebude fungovat, kdyz cil symlinku bude taky symlink, ani kdyz to spustim z jineho mista nez kde je ten konecny soubor
cesta=`ls -l $1 | cut -d">" -f2 | xargs -I {} ls -l {} | cut -d" " -f-9`
echo $cesta $1

# reseni dle knizky
adr=`pwd`
puvodni=$1
case $1:$adr in       # vytvoreni stringu pro test parametru i aktualniho adresare; podminky pak pro oba testovane vyrazy
/* ) cesta=$1;;       # pokud $1 zacina lomitkem, tj. parametrem je absolutni cesta, tj. /home/user/Downloads/nazev_linku
*/ ) cesta=/$1;;      # cesta je relativni a nachazime se v koreni stromu adresaru ../../nazev_linku a $adr konci na /
*  ) cesta=$adr/$1;;  # relativni cesta a nekorenovy adresar; slouceni adresare a nazvu souboru
esac

while [ -L "$cesta" ]; do  # -L soubor existuje a je to symlink
	# zjisti se, kam symlink smeruje + pomoci sed se vymaze zacatek radku az po sipku
	odkaz=`ls -ld $cesta | sed "s:.* $cesta -> ::"`
	case odkaz in
	/* ) cesta=$odkaz;;
	*  ) cesta=`echo "$cesta" | sed 's:/[^/]*$::'`/$odkaz;;
	esac
done

if [ -e "$cesta" ]; then
	ls -ld "$cesta" | sed "s:$cesta\$:$puvodni:"
else
	ls -ld  "$puvodni"
fi




