#!/bin/bash

# $1 je slozka, kde se v souborech zmeni v nazvu mezery za _
# pozor na pripadne presunuti souboru do jine slozky stejneho jmena

for file in "$1"*
do
	echo "$file" | tr -s ' ' '_' | xargs -I {} mv "$file" {}
done
